name: work38
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.8.13
  - pytorch==1.12.1
  - cudatoolkit=11.6
  - torchvision
  - torchaudio
  - jupyter
  - pandas
  - sqlalchemy
  - tqdm
  - dill
  - psycopg2
  - ray-tune
